services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: richcorp_app
    # user: django
    restart: unless-stopped
    volumes:
      - static-data:/app/static
      - media-data:/app/media
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_NAME=richcorpdb
      - DB_USER=richcorpuser
      - DB_PASS_FILE=/run/secrets/db_password
      - DEBUG=0
      - REDIS_PASSWORD=my&redis!secret
    depends_on:
      - db
      - redis
      # - daphne
      # - gunicorn
      - celery_worker
      - celery_beat
    networks:
      - my_network
    secrets:
      - db_password

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    # user: celery
    environment:
      - DJANGO_SETTINGS_MODULE=richcorp.settings_conf.production
      - REDIS_PASSWORD=my&redis!secret
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
      - redis
    networks:
      - my_network
    secrets:
      - db_password

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.celery.beat
    # user: celery
    environment:
      - DJANGO_SETTINGS_MODULE=richcorp.settings_conf.production
      - REDIS_PASSWORD=my&redis!secret
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
      - redis
    networks:
      - my_network
    secrets:
      - db_password

  # daphne:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.daphne
  #   # user: daphne
  #   environment:
  #     - REDIS_PASSWORD=my&redis!secret
  #   depends_on:
  #     - db
  #     - redis
  #   networks:
  #     - my_network
  #   secrets:
  #     - db_password

  # gunicorn:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.gunicorn
    # environment:
    #   - REDIS_PASSWORD=my&redis!secret
    # depends_on:
    #   - db
    #   - redis
    # networks:
    #   - my_network
    # secrets:
    #   - db_password

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - static-data:/app/static:ro
      - media-data:/app/media:ro
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # - certbot-etc:/etc/letsencrypt:ro
      # - certbot-var:/var/lib/letsencrypt:ro
      # - ./certbot/www:/var/www/certbot:ro

      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/var:/var/lib/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - django
      - certbot
      - pgadmin
    networks:
      - my_network

  certbot:
    image: certbot/certbot
    volumes:
      # - certbot-etc:/etc/letsencrypt
      # - certbot-var:/var/lib/letsencrypt
      # - ./certbot/www:/var/www/certbot
      # - ./nginx/openssl.cnf:/etc/ssl/openssl.cnf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx/openssl.cnf:/etc/ssl/openssl.cnf
      
    command: certonly --webroot -w /var/www/certbot 
              -d richcorporationsa.com 
              -d www.richcorporationsa.com 
              -d pgadmin.richcorporationsa.com  
              -d api.richcorporationsa.com   
              --email pepexykabasele@gmail.com 
              --agree-tos --force-renewal --non-interactive
    networks:
      - my_network

  certbot-renew:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done;'"
    networks:
      - my_network


  redis:
     image: redis:latest
     ports:
       - "6379:6379"
     networks:
       - my_network

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=richcorpdb
      - POSTGRES_USER=richcorpuser
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U richcorpuser -d richcorpdb -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_network
    secrets:
      - db_password

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_server
    ports:
      - 5051:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    depends_on:
      - db
    networks:
      - my_network


volumes:
  dev-db-data:
  static-data:
  media-data:
  certbot-etc:
  certbot-var:
  redis-data:

networks:
  my_network:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt
  pgadmin_password:
    file: ./secrets/pgadmin_password.txt
