services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: richcorp_app
    restart: unless-stopped
    volumes:
      - static-data:/app/static
      - media-data:/app/media
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=richcorp.settings_conf.production
      - REDIS_PASSWORD=my&redis!secret
    # command: sh -lc "python manage.py migrate && python manage.py collectstatic --noinput  --workers 3 --timeout 120"
    depends_on:
      - db
      - redis
    networks:
      - my_network
    secrets:
      - db_password

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=richcorp.settings_conf.production
      - REDIS_PASSWORD=my&redis!secret
    depends_on:
      - db
      - redis
    networks:
      - my_network
    secrets:
      - db_password

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.celery.beat
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=richcorp.settings_conf.production
      - REDIS_PASSWORD=my&redis!secret
    depends_on:
      - db
      - redis
    networks:
      - my_network
    secrets:
      - db_password

  nginx:
    image: nginx:latest
    container_name: richcorp_nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - static-data:/app/static:ro
      - media-data:/app/media:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - django
      - pgadmin
    networks:
      - my_network

  certbot-renew:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h; done;"
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: richcorp_redis
    ports:
      - "6379:6379"
    networks:
      - my_network

  db:
    image: postgres:13-alpine
    container_name: richcorp_db
    restart: unless-stopped
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=richcorpdb
      - POSTGRES_USER=richcorpuser
      - POSTGRES_PASSWORD_FILE=richcorppass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U richcorpuser -d richcorpdb -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_network
    secrets:
      - db_password

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_server
    restart: unless-stopped
    ports:
      - "5051:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    depends_on:
      - db
    networks:
      - my_network

volumes:
  dev-db-data:
  static-data:
  media-data:

networks:
  my_network:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt
